//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Table
    {
        public int Project_id { get; set; }
        public string Project_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string manager_name { get; set; }
    }
}
