//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManager.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Table
    {
        public int Task_id { get; set; }
        public string Project_Name { get; set; }
        public string Task_name { get; set; }
        public Nullable<bool> Is_parent_task { get; set; }
        public Nullable<int> Priority { get; set; }
        public string parent_task_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_name { get; set; }
        public string status { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Task_Table Task_Table1 { get; set; }
        public virtual Task_Table Task_Table2 { get; set; }
    }
}
